# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('gui', 'gui'),
        ('venv/Lib/site-packages/safehttpx/version.txt', 'safehttpx'),
        ('venv/Lib/site-packages/groovy/version.txt', 'groovy'),
        ('venv/Lib/site-packages/gradio', 'gradio'),
        ('venv/Lib/site-packages/gradio_client', 'gradio_client'),
        ('venv/Lib/site-packages/spacy/lang', 'spacy/lang'),
        ('venv/Lib/site-packages/en_core_web_sm', 'en_core_web_sm'),
        ('venv/Lib/site-packages/sentence_transformers', 'sentence_transformers'),
        ('venv/Lib/site-packages/chromadb', 'chromadb'),
        ('venv/Lib/site-packages/tokenizers', 'tokenizers'),
        ('venv/Lib/site-packages/thinc', 'thinc'),
        ('core/system_prompt.txt', 'core'),
        ('config/config.yaml', 'config'),
    ],
    hiddenimports=[
        'posthog',
        'chromadb_rust_bindings',
        'chromadb.api.rust',
        'chromadb.api.segment',
        'chromadb.db.impl',
        'chromadb.db.impl.sqlite',
        'chromadb.segment.impl',
        'chromadb.segment.impl.manager',
        'chromadb.segment.impl.manager.local',
        'chromadb.segment.impl.metadata',
        'chromadb.segment.impl.vector',
        'chromadb.telemetry.product.posthog',
        'chromadb.ingest.impl',
        'chromadb.quota.impl',
        'gui.wizard',
        'onnxruntime',
        'tokenizers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# Splash screen - text positioned at left edge so it stays visible
splash = Splash(
    'splash.png',
    binaries=a.binaries,
    datas=a.datas,
    text_pos=(10, 170),
    text_size=10,
    text_color='#888888',
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    splash,
    a.binaries,
    a.datas,
    splash.binaries,
    [],
    name='Daemon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='daemon.ico',
)
