# memory/code_proposal.py
"""
Code Proposal schema for goal-directed code generation and branch supervision.

Module Contract
- Purpose: Data models for code change proposals generated by LLM analysis
  of project goals, skeleton, and recent activity. Stored in ChromaDB
  'proposals' collection for semantic retrieval and deduplication.
  Enriched with supervision fields (risk_level, touches_core_system,
  depends_on, test_files, outcome) for human-in-the-loop branch gating.
- Inputs: Raw dicts from LLM JSON output (via from_dict / from_metadata)
- Outputs: Serializable proposal objects with status lifecycle management
- Key behaviors:
  - Pydantic-validated fields with sensible defaults
  - to_metadata() / from_metadata() for ChromaDB storage (flat primitives)
  - to_dict() / from_dict() for full JSON serialization (tests, export)
  - Status lifecycle: PENDING -> APPROVED -> COMPLETED (or REJECTED/FAILED)
  - Supervision fields: RiskLevel, ProposalOutcome, depends_on, test_files,
    touches_core_system — used by main branch to gate sub-branch merges
- Side effects: None (pure data model)
"""

import json
import time
import uuid
from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ProposalType(str, Enum):
    """Type of code change being proposed."""
    FEATURE = "feature"
    REFACTOR = "refactor"
    BUGFIX = "bugfix"
    TEST = "test"
    DOCS = "docs"
    INFRA = "infra"


class ProposalStatus(str, Enum):
    """Lifecycle status of a proposal."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    COMPLETED = "completed"
    FAILED = "failed"


class ProposalSource(str, Enum):
    """How the proposal was generated."""
    GOAL_DIRECTED = "goal_directed"
    SESSION_INSIGHT = "session_insight"
    USER_REQUEST = "user_request"
    SHUTDOWN_ANALYSIS = "shutdown_analysis"
    AGENT_BRANCH = "agent_branch"


class RiskLevel(str, Enum):
    """Risk assessment for merge gating."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ImplementationStep(BaseModel):
    """A single step in a proposal's implementation plan."""

    order: int = Field(..., description="Step sequence number (1-based)")
    description: str = Field(..., description="What this step does")
    file_path: str = Field(default="", description="Target file path (if applicable)")
    action: str = Field(
        default="modify",
        description="Action type: create, modify, delete, test",
    )
    code_snippet: str = Field(
        default="",
        description="Optional code snippet or pseudocode for this step",
    )

    def to_dict(self) -> dict:
        return {
            "order": self.order,
            "description": self.description,
            "file_path": self.file_path,
            "action": self.action,
            "code_snippet": self.code_snippet,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ImplementationStep":
        return cls(
            order=int(data.get("order", 1)),
            description=data.get("description", ""),
            file_path=data.get("file_path", ""),
            action=data.get("action", "modify"),
            code_snippet=data.get("code_snippet", ""),
        )


class ProposalOutcome(BaseModel):
    """Structured outcome record for completed/rejected proposals."""

    accepted: bool = Field(default=False, description="Whether the proposal was accepted/merged")
    notes: str = Field(default="", description="Human reviewer notes")
    merged_at: Optional[float] = Field(default=None, description="Timestamp of merge to main")
    merge_branch: str = Field(default="", description="Branch that was merged from")
    reviewed_by: str = Field(default="", description="Who reviewed (human or supervisor ID)")

    def to_dict(self) -> dict:
        return {
            "accepted": self.accepted,
            "notes": self.notes,
            "merged_at": self.merged_at,
            "merge_branch": self.merge_branch,
            "reviewed_by": self.reviewed_by,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ProposalOutcome":
        return cls(
            accepted=bool(data.get("accepted", False)),
            notes=data.get("notes", ""),
            merged_at=data.get("merged_at"),
            merge_branch=data.get("merge_branch", ""),
            reviewed_by=data.get("reviewed_by", ""),
        )


class CodeProposal(BaseModel):
    """
    A proposed code change with reasoning, steps, and lifecycle tracking.

    Stored in ChromaDB 'proposals' collection.
    Embedding text is generated from title + reasoning (problem context);
    full implementation details are stored in metadata.

    Supervision fields (risk_level, touches_core_system, depends_on,
    test_files, outcome) support human-in-the-loop branch gating:
    sub-branches can push to themselves but require main-branch approval
    to merge, informed by these fields.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str = Field(..., description="Short descriptive title", min_length=3, max_length=200)
    proposal_type: ProposalType = Field(default=ProposalType.FEATURE)
    status: ProposalStatus = Field(default=ProposalStatus.PENDING)
    source: ProposalSource = Field(default=ProposalSource.GOAL_DIRECTED)
    priority: int = Field(default=5, ge=1, le=10, description="Priority 1-10 (10 = highest)")
    reasoning: str = Field(default="", description="Why this change is needed")
    description: str = Field(default="", description="Detailed description of the change")
    implementation_steps: List[ImplementationStep] = Field(default_factory=list)
    affected_files: List[str] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    estimated_complexity: str = Field(
        default="medium",
        description="Complexity estimate: low, medium, high",
    )
    requires_tests: bool = Field(default=True)
    rejection_reason: str = Field(default="")
    commit_hash: str = Field(default="")
    rollback_available: bool = Field(default=False)
    created_at: float = Field(default_factory=time.time)
    modified_at: float = Field(default_factory=time.time)
    executed_at: Optional[float] = Field(default=None)
    implementation_confidence: float = Field(default=0.0)
    implementation_status: str = Field(default="not_checked")
    implementation_evidence: str = Field(default="")
    last_tracked_at: Optional[float] = Field(default=None)

    # --- Supervision fields (branch gating) ---
    risk_level: RiskLevel = Field(
        default=RiskLevel.MEDIUM,
        description="Risk assessment: low, medium, high, critical",
    )
    touches_core_system: bool = Field(
        default=False,
        description="Whether the proposal modifies core orchestration, memory, or safety code",
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="Proposal IDs that must be completed before this one",
    )
    test_files: List[str] = Field(
        default_factory=list,
        description="Actual test file paths that validate this proposal",
    )
    outcome: Optional[ProposalOutcome] = Field(
        default=None,
        description="Structured outcome after review (acceptance, merge notes, reviewer)",
    )

    def to_embedding_text(self) -> str:
        """
        Generate text for embedding. Focuses on TITLE + REASONING (problem
        context) + TAGS. Implementation details are stored in metadata,
        not embedded — we match on problem, not solution.
        """
        tag_str = ", ".join(self.tags) if self.tags else ""
        parts = [f"Proposal: {self.title}"]
        if self.reasoning:
            parts.append(f"Reasoning: {self.reasoning}")
        if tag_str:
            parts.append(f"Tags: {tag_str}")
        parts.append(f"Type: {self.proposal_type.value}")
        if self.risk_level in (RiskLevel.HIGH, RiskLevel.CRITICAL):
            parts.append(f"Risk: {self.risk_level.value}")
        if self.touches_core_system:
            parts.append("Core-system change")
        return " | ".join(parts)

    def to_metadata(self) -> dict:
        """
        Serialize for ChromaDB metadata storage.
        Lists and nested objects are JSON-serialized since ChromaDB
        only supports primitive metadata values.
        """
        return {
            "proposal_id": self.id,
            "title": self.title,
            "proposal_type": self.proposal_type.value,
            "status": self.status.value,
            "source": self.source.value,
            "priority": self.priority,
            "reasoning": self.reasoning[:1000],  # cap for metadata size
            "description": self.description[:2000],
            "estimated_complexity": self.estimated_complexity,
            "requires_tests": self.requires_tests,
            "rejection_reason": self.rejection_reason,
            "commit_hash": self.commit_hash,
            "rollback_available": self.rollback_available,
            "tags_json": json.dumps(self.tags),
            "affected_files_json": json.dumps(self.affected_files),
            "steps_json": json.dumps([s.to_dict() for s in self.implementation_steps]),
            "created_at": self.created_at,
            "modified_at": self.modified_at,
            "executed_at": self.executed_at or 0.0,
            "implementation_confidence": self.implementation_confidence,
            "implementation_status": self.implementation_status,
            "implementation_evidence": self.implementation_evidence[:500],
            "last_tracked_at": self.last_tracked_at or 0.0,
            # Supervision fields
            "risk_level": self.risk_level.value,
            "touches_core_system": self.touches_core_system,
            "depends_on_json": json.dumps(self.depends_on),
            "test_files_json": json.dumps(self.test_files),
            "outcome_json": json.dumps(self.outcome.to_dict() if self.outcome else None),
        }

    @classmethod
    def from_metadata(cls, metadata: dict) -> "CodeProposal":
        """Deserialize from ChromaDB metadata."""
        steps_raw = json.loads(metadata.get("steps_json", "[]"))
        steps = [ImplementationStep.from_dict(s) for s in steps_raw]

        # Parse outcome (may be absent in pre-supervision proposals)
        outcome_raw = json.loads(metadata.get("outcome_json", "null"))
        outcome = ProposalOutcome.from_dict(outcome_raw) if outcome_raw else None

        return cls(
            id=metadata.get("proposal_id", str(uuid.uuid4())),
            title=metadata.get("title", "Untitled"),
            proposal_type=ProposalType(metadata.get("proposal_type", "feature")),
            status=ProposalStatus(metadata.get("status", "pending")),
            source=ProposalSource(metadata.get("source", "goal_directed")),
            priority=int(metadata.get("priority", 5)),
            reasoning=metadata.get("reasoning", ""),
            description=metadata.get("description", ""),
            implementation_steps=steps,
            affected_files=json.loads(metadata.get("affected_files_json", "[]")),
            tags=json.loads(metadata.get("tags_json", "[]")),
            estimated_complexity=metadata.get("estimated_complexity", "medium"),
            requires_tests=bool(metadata.get("requires_tests", True)),
            rejection_reason=metadata.get("rejection_reason", ""),
            commit_hash=metadata.get("commit_hash", ""),
            rollback_available=bool(metadata.get("rollback_available", False)),
            created_at=float(metadata.get("created_at", time.time())),
            modified_at=float(metadata.get("modified_at", time.time())),
            executed_at=float(metadata["executed_at"]) or None
            if metadata.get("executed_at")
            else None,
            implementation_confidence=float(metadata.get("implementation_confidence", 0.0)),
            implementation_status=metadata.get("implementation_status", "not_checked"),
            implementation_evidence=metadata.get("implementation_evidence", ""),
            last_tracked_at=float(metadata["last_tracked_at"]) or None
            if metadata.get("last_tracked_at")
            else None,
            # Supervision fields
            risk_level=RiskLevel(metadata.get("risk_level", "medium")),
            touches_core_system=bool(metadata.get("touches_core_system", False)),
            depends_on=json.loads(metadata.get("depends_on_json", "[]")),
            test_files=json.loads(metadata.get("test_files_json", "[]")),
            outcome=outcome,
        )

    def to_dict(self) -> dict:
        """Full serialization for JSON export / testing."""
        return {
            "id": self.id,
            "title": self.title,
            "proposal_type": self.proposal_type.value,
            "status": self.status.value,
            "source": self.source.value,
            "priority": self.priority,
            "reasoning": self.reasoning,
            "description": self.description,
            "implementation_steps": [s.to_dict() for s in self.implementation_steps],
            "affected_files": self.affected_files,
            "tags": self.tags,
            "estimated_complexity": self.estimated_complexity,
            "requires_tests": self.requires_tests,
            "rejection_reason": self.rejection_reason,
            "commit_hash": self.commit_hash,
            "rollback_available": self.rollback_available,
            "created_at": self.created_at,
            "modified_at": self.modified_at,
            "executed_at": self.executed_at,
            "implementation_confidence": self.implementation_confidence,
            "implementation_status": self.implementation_status,
            "implementation_evidence": self.implementation_evidence,
            "last_tracked_at": self.last_tracked_at,
            # Supervision fields
            "risk_level": self.risk_level.value,
            "touches_core_system": self.touches_core_system,
            "depends_on": self.depends_on,
            "test_files": self.test_files,
            "outcome": self.outcome.to_dict() if self.outcome else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CodeProposal":
        """Deserialize from a full dict (inverse of to_dict)."""
        steps_raw = data.get("implementation_steps", [])
        steps = [
            ImplementationStep.from_dict(s) if isinstance(s, dict) else s
            for s in steps_raw
        ]

        # Parse outcome (may be absent in pre-supervision proposals)
        outcome_raw = data.get("outcome")
        outcome = (
            ProposalOutcome.from_dict(outcome_raw)
            if isinstance(outcome_raw, dict)
            else None
        )

        return cls(
            id=data.get("id", str(uuid.uuid4())),
            title=data.get("title", "Untitled"),
            proposal_type=ProposalType(data.get("proposal_type", "feature")),
            status=ProposalStatus(data.get("status", "pending")),
            source=ProposalSource(data.get("source", "goal_directed")),
            priority=int(data.get("priority", 5)),
            reasoning=data.get("reasoning", ""),
            description=data.get("description", ""),
            implementation_steps=steps,
            affected_files=data.get("affected_files", []),
            tags=data.get("tags", []),
            estimated_complexity=data.get("estimated_complexity", "medium"),
            requires_tests=bool(data.get("requires_tests", True)),
            rejection_reason=data.get("rejection_reason", ""),
            commit_hash=data.get("commit_hash", ""),
            rollback_available=bool(data.get("rollback_available", False)),
            created_at=float(data.get("created_at", time.time())),
            modified_at=float(data.get("modified_at", time.time())),
            executed_at=data.get("executed_at"),
            implementation_confidence=float(data.get("implementation_confidence", 0.0)),
            implementation_status=data.get("implementation_status", "not_checked"),
            implementation_evidence=data.get("implementation_evidence", ""),
            last_tracked_at=data.get("last_tracked_at"),
            # Supervision fields
            risk_level=RiskLevel(data.get("risk_level", "medium")),
            touches_core_system=bool(data.get("touches_core_system", False)),
            depends_on=data.get("depends_on", []),
            test_files=data.get("test_files", []),
            outcome=outcome,
        )

    # ------------------------------------------------------------------
    # Status lifecycle methods
    # ------------------------------------------------------------------

    def mark_approved(self) -> None:
        """Transition to APPROVED status."""
        self.status = ProposalStatus.APPROVED
        self.modified_at = time.time()

    def mark_rejected(self, reason: str = "") -> None:
        """Transition to REJECTED status with optional reason."""
        self.status = ProposalStatus.REJECTED
        self.rejection_reason = reason
        self.modified_at = time.time()

    def mark_completed(self, commit_hash: str = "") -> None:
        """Transition to COMPLETED status after successful execution."""
        self.status = ProposalStatus.COMPLETED
        self.commit_hash = commit_hash
        self.executed_at = time.time()
        self.rollback_available = bool(commit_hash)
        self.modified_at = time.time()

    def mark_failed(self, error: str = "") -> None:
        """Transition to FAILED status after execution failure."""
        self.status = ProposalStatus.FAILED
        self.rejection_reason = f"Execution failed: {error}" if error else "Execution failed"
        self.modified_at = time.time()

    def record_outcome(
        self,
        accepted: bool,
        notes: str = "",
        merge_branch: str = "",
        reviewed_by: str = "",
    ) -> None:
        """Record the human review outcome for this proposal."""
        self.outcome = ProposalOutcome(
            accepted=accepted,
            notes=notes,
            merged_at=time.time() if accepted else None,
            merge_branch=merge_branch,
            reviewed_by=reviewed_by,
        )
        if accepted:
            self.status = ProposalStatus.COMPLETED
        else:
            self.status = ProposalStatus.REJECTED
            if notes:
                self.rejection_reason = notes
        self.modified_at = time.time()
