daemon:
  version: v4
  data_dir: ./data
  log_dir: ./conversation_logs
  in_harm_test: false
  debug_mode: true
  device: cuda
memory:
  corpus_file: ./data/corpus_v4.json
  chroma_path: ./data/chroma_db_v4
  max_recent: 50
  max_memories: 8
  max_final_memories: 2
  max_working_memory: 8
  mem_no: 5
  mem_importance_score: 0.75
  num_memories: 10
  child_mem_limit: 3
  recency_decay_rate: 0.1
  truth_score_update_rate: 0.02
  truth_score_max: 0.95
  collection_boosts:
    facts: 0.1
    summaries: 0.1
    conversations: 0.3
    semantic: 0.05
    wiki: 0.05
  default_summary_prompt_header: 'Summary of last 20 exchanges:

    '
  default_tagging_prompt: 'You are Daemon, my assistant. Extract 5 concise tags or
    keywords from the following input. Return them as a list, comma-separated.

    Input: "{text}"

    Tags:

    '
  retrieve_conversations: true
  max_conversations: 10
  conversation_collection: conversations
  retrieve_summaries: true
  max_summaries: 10
  summary_collection: summaries
  summary_interval: 20
  max_facts: 15
  max_reflections: 6
models:
  default: llama
  dream_model: gpt-neo
  openrouter_base: https://openrouter.ai/api/v1
  load_local_model: true
  local_model_context_limit: 4096
  api_model_context_limit: 128000
  default_max_tokens: 8192
  default_top_p: 0.9
  default_top_k: 5
  default_temperature: 1.5
  openai_api_key: ''
  active: claude-opus
gating:
  confidence_threshold: 2.0
  gate_rel_threshold: 0.25
  cosine_threshold: 0.25
  cosine_similarity_threshold: 0.45
  deictic_threshold: 0.75
  normal_threshold: 0.55
  deictic_anchor_penalty: 0.25
  deictic_continuity_min: 0.25
  use_reranking: true
  rerank_use_llm: false
  cross_encoder_weight: 0.9
  topic_confidence_threshold: 0.85
  score_weights:
    relevance: 0.55
    recency: 0.3
    truth: 0.15
    importance: 0.0
    continuity: 0.03
    structure: 0.02
paths:
  system_prompt: core/system_prompt.txt
  directives: structured_directives.txt
  system_prompt_file:
    name: daemon
    system_prompt_file: /home/lukeh/Daemon_RAG_Agent_working/core/system_prompt.txt
features:
  enable_wikipedia: true
  enable_semantic_search: true
  enable_facts: true
  enable_dreams: false
  semantic_only_mode: false
  enable_best_of: false
  enable_query_rewrite: true
  disable_llm_summaries: false
  best_of_latency_budget_s: 4.0
  rewrite_timeout_s: 0
  best_of_model: gpt-4o
  best_of_max_tokens: 8816
  best_of_min_question: false
  best_of_generator_models:
  - gpt-5
  - claude-opus
  best_of_selector_models:
  - gpt-4o-mini
  - gpt-4.1
  best_of_selector_weights:
    heuristic: 0.4
    llm: 0.6
  best_of_selector_top_k: 0
  best_of_selector_max_tokens: 80
  best_of_duel_mode: true
prompts:
  default_system_prompt: You are Daemon, a brutally honest AI assistant who tells
    the truth even when uncomfortable, admits ignorance freely, and uses dark humor
    about current events. You're willing to call out BS while still being genuinely
    helpful.
  system_prompt: ''
  default_core_directive:
    query: '[CORE DIRECTIVE]'
    response: You are an AI assistant. You are helpful, reliable, and memory-persistent.
      You should respect user intent and be aligned with their goals.
    timestamp: ''
    tags:
    - '@seed'
    - core
    - directive
    - safety
