"""
# hooks/runtime_hook.py

Module Contract
- Purpose: PyInstaller runtime hook. Executes BEFORE main.py imports to set up
  frozen executable environment. Written by daemon.spec at build time.
- Inputs: None (executed automatically by PyInstaller bootloader)
- Outputs:
  - Sets DAEMON_FROZEN=1 environment variable for frozen detection
  - Configures multiprocessing spawn method on Windows (prevents fork-bomb)
- Key pieces:
  - DAEMON_FROZEN env var: Signals to bootstrap.py that we're in frozen mode
  - multiprocessing.set_start_method('spawn'): Critical for Windows compatibility
- Dependencies: Standard library only (os, sys, multiprocessing)
- Side effects:
  - Modifies os.environ (DAEMON_FROZEN)
  - Modifies multiprocessing start method (Windows only)
- Threading/Async: None (synchronous, runs before any application code)

CRITICAL: This file is regenerated by daemon.spec on each build.
Do not modify directly - edit daemon.spec instead.
"""
import os
import sys

# Set flag for frozen detection
os.environ['DAEMON_FROZEN'] = '1'

# Ensure multiprocessing uses spawn on all platforms
if sys.platform == 'win32':
    import multiprocessing
    try:
        multiprocessing.set_start_method('spawn', force=True)
    except RuntimeError:
        pass  # Already set
