# /utils/web_search_trigger.py
"""
WebSearchTrigger - Detects when a query should trigger web search or memory search.

Module Contract:
- Purpose: Classify queries to determine if they need real-time web information or stored memory recall
- Inputs:
  - Query text
  - Optional: model_manager (for LLM classification)
  - Optional: crisis_level, remaining_credits, web_search_enabled
- Outputs:
  - WebSearchDecision with:
    - should_search: bool
    - depth: WebSearchDepth (QUICK/STANDARD/DEEP)
    - confidence: float (0.0-1.0)
    - search_terms: List[str] (LLM-optimized queries for better results)
    - num_searches: int (parallel search count, 1-4)
    - source: str ("llm" | "heuristic" | "explicit")
    - needs_memory_search: bool (LLM detected memory/recall intent) [NEW 2026-03-15]
- Side effects:
  - LLM API call when using analyze_for_web_search_llm() (async)
  - None for heuristic-only path

Detection Strategy (LLM-First with Heuristic Fallback):
1. Crisis suppression: Block search during HIGH/MEDIUM crisis levels
2. Quick pre-filter: Skip LLM for obvious non-search queries (conversational, emotional)
3. LLM classification: Single call returns should_search + needs_memory_search + optimized search_terms + depth
4. Confidence blend: 70% LLM + 30% heuristic for final decision
5. Heuristic fallback: On LLM timeout/error, use keyword-based detection

Legacy Heuristic Detection (fallback):
1. Keyword matching for recency indicators ("latest", "current", "2024", etc.)
2. Pattern matching for news/event queries
3. Entity detection for fast-changing topics (stocks, weather, sports scores)
4. Explicit search requests ("search for", "look up online")
"""

import asyncio
import os
import re
import time
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Set, Tuple

from utils.logging_utils import get_logger

logger = get_logger("web_search_trigger")

# Short-lived cache for LLM trigger results (prevents duplicate calls within same request)
# Structure: {query_hash: (timestamp, WebSearchDecision)}
_llm_trigger_cache: Dict[int, Tuple[float, "WebSearchDecision"]] = {}
_LLM_TRIGGER_CACHE_TTL = 10.0  # 10 seconds - long enough for same request, short enough to not stale


class WebSearchDepth(Enum):
    """Search depth levels - mirrored from web_search_manager for decoupling."""
    QUICK = "quick"
    STANDARD = "standard"
    DEEP = "deep"


@dataclass
class WebSearchDecision:
    """
    Result of web search trigger analysis.

    Attributes:
        should_search: Whether to trigger web search
        depth: Recommended search depth (QUICK/STANDARD/DEEP)
        confidence: Decision confidence score (0.0-1.0)
        reason: Human-readable explanation for decision
        matched_keywords: Keywords that matched (for heuristic debugging)
        matched_patterns: Patterns that matched (for heuristic debugging)
        search_terms: LLM-optimized search queries (empty if heuristic-only)
        num_searches: Number of parallel searches to execute (1-4)
        source: Decision source ("llm" | "heuristic" | "explicit")
    """
    should_search: bool
    depth: WebSearchDepth
    confidence: float  # 0.0-1.0
    reason: str
    matched_keywords: List[str]
    matched_patterns: List[str]
    # LLM-first fields
    search_terms: List[str] = None  # LLM-optimized search queries
    num_searches: int = 1  # Parallel search count (1-4)
    source: str = "heuristic"  # "llm" | "heuristic" | "explicit"
    needs_memory_search: bool = False  # LLM detected memory/recall intent

    def __post_init__(self):
        """Initialize mutable defaults."""
        if self.search_terms is None:
            self.search_terms = []


@dataclass
class LLMSearchTriggerResponse:
    """
    Parsed response from unified LLM trigger classification.

    This dataclass represents the structured output from the LLM when
    it analyzes a query for web search needs. The LLM returns JSON that
    gets parsed into this structure.

    Attributes:
        should_search: Whether the query needs web search
        confidence: LLM's confidence in the decision (0.0-1.0)
        reason: Brief explanation of the decision
        search_terms: Optimized search queries generated by LLM
        search_depth: Recommended depth ("quick" | "standard" | "deep")
        num_searches: How many parallel searches to execute (1-4)
    """
    should_search: bool
    confidence: float
    reason: str
    search_terms: List[str]
    search_depth: str  # "quick" | "standard" | "deep"
    num_searches: int
    needs_memory_search: bool = False  # Whether query wants stored memories/facts/notes

    @classmethod
    def parse(cls, json_str: str) -> Optional['LLMSearchTriggerResponse']:
        """
        Parse LLM JSON response with error handling.

        Handles common issues:
        - Markdown code blocks (```json...```)
        - Missing fields (uses safe defaults)
        - Invalid JSON (returns None for fallback to heuristics)

        Args:
            json_str: Raw JSON string from LLM response

        Returns:
            LLMSearchTriggerResponse if parsing succeeds, None otherwise
        """
        import json

        if not json_str:
            return None

        # Strip markdown code blocks if present
        text = json_str.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            text = "\n".join(lines)

        try:
            data = json.loads(text)

            # Validate and clamp values
            confidence = float(data.get("confidence", 0.0))
            confidence = max(0.0, min(1.0, confidence))

            num_searches = int(data.get("num_searches", 1))
            num_searches = max(1, min(4, num_searches))

            search_depth = str(data.get("search_depth", "quick")).lower()
            if search_depth not in ("quick", "standard", "deep"):
                search_depth = "quick"

            return cls(
                should_search=bool(data.get("should_search", False)),
                confidence=confidence,
                reason=str(data.get("reason", "")),
                search_terms=list(data.get("search_terms", [])),
                search_depth=search_depth,
                num_searches=num_searches,
                needs_memory_search=bool(data.get("needs_memory_search", False))
            )
        except (json.JSONDecodeError, ValueError, TypeError) as e:
            logger.debug(f"[LLMSearchTriggerResponse] JSON parse error: {e}")
            return None


# ===== Configuration =====

# Minimum confidence to trigger search
SEARCH_CONFIDENCE_THRESHOLD = float(os.getenv("WEB_SEARCH_CONFIDENCE_THRESHOLD", "0.5"))

# LLM classification settings
SEARCH_TRIGGER_MODEL = os.getenv("WEB_SEARCH_TRIGGER_MODEL", "gpt-4o-mini")
SEARCH_TRIGGER_TIMEOUT = float(os.getenv("WEB_SEARCH_TRIGGER_TIMEOUT", "5.0"))  # Increased from 2.0
SEARCH_TRIGGER_MAX_TOKENS = int(os.getenv("WEB_SEARCH_TRIGGER_MAX_TOKENS", "150"))

# LLM-first mode settings
LLM_FIRST_ENABLED = os.getenv("WEB_SEARCH_LLM_FIRST_ENABLED", "true").lower() == "true"
LLM_HEURISTIC_BLEND_WEIGHT = float(os.getenv("WEB_SEARCH_LLM_WEIGHT", "0.7"))  # 70% LLM, 30% heuristic


# ===== Keyword Sets =====

# Strong recency indicators - high confidence triggers
RECENCY_KEYWORDS_STRONG: Set[str] = {
    "latest", "newest", "most recent", "current", "today",
    "this week", "this month", "right now", "breaking",
    "just announced", "just released", "just happened",
    "happening now", "live", "real-time", "realtime",
}

# Moderate recency indicators
RECENCY_KEYWORDS_MODERATE: Set[str] = {
    "recent", "new", "updated", "modern", "contemporary",
    "this year", "last week", "yesterday", "recently",
    "nowadays", "these days", "currently",
}

# Year patterns that suggest recency needs
CURRENT_YEAR = datetime.now().year
RECENT_YEARS = {str(CURRENT_YEAR), str(CURRENT_YEAR - 1)}

# Explicit search request phrases
EXPLICIT_SEARCH_PHRASES: Tuple[str, ...] = (
    "search for", "look up", "find online", "search online",
    "google", "search the web", "web search", "internet search",
    "find me information", "find information about",
    "what's happening with", "what's going on with",
    "check online", "look online",
)

# News and event indicators
NEWS_KEYWORDS: Set[str] = {
    "news", "headline", "headlines", "story", "stories",
    "reported", "reports", "announced", "announcement",
    "update", "updates", "press release", "breaking",
    "coverage", "article", "articles",
}

# Fast-changing topics that often need fresh data
FAST_CHANGING_TOPICS: Set[str] = {
    # Financial
    "stock", "stocks", "share price", "stock price", "market",
    "bitcoin", "crypto", "cryptocurrency", "ethereum", "btc", "eth",
    "exchange rate", "forex", "trading",

    # Weather
    "weather", "forecast", "temperature", "rain", "storm",
    "hurricane", "tornado", "snow", "climate",

    # Sports
    "score", "scores", "game", "match", "tournament",
    "championship", "playoffs", "standings", "roster",
    "injury", "trade", "transfer",

    # Tech/Product
    "release date", "launch date", "availability",
    "version", "update", "patch", "beta", "alpha",

    # Events
    "election", "vote", "voting", "poll", "polls",
    "concert", "event", "festival", "conference",
    "sale", "discount", "deal", "price drop",
}

# Topics that typically DON'T need web search (knowledge-based)
STATIC_TOPICS: Set[str] = {
    # Historical/factual
    "history", "historical", "ancient", "medieval",
    "biography", "born", "died", "founded",

    # Scientific concepts
    "theory", "theorem", "formula", "equation",
    "chemistry", "physics", "biology", "mathematics",
    "element", "compound", "molecule", "atom",

    # Definitions/concepts
    "definition", "meaning", "what is", "explain",
    "concept", "principle", "law of",

    # How-to/procedural
    "how to", "how do i", "tutorial", "guide",
    "recipe", "instructions", "steps",

    # Creative/personal
    "write me", "create", "generate", "compose",
    "help me with", "advice on", "opinion",
}

# Suppression patterns - don't search for these
SUPPRESSION_PATTERNS: Tuple[str, ...] = (
    # Personal/conversational
    "how are you", "how do you feel", "what do you think",
    "tell me about yourself", "who are you",

    # Memory/context queries
    "remember when", "do you remember", "recall",
    "we talked about", "you mentioned", "earlier",

    # Emotional/therapeutic
    "feeling", "I feel", "I'm feeling", "i am feeling",
    "stressed", "anxious", "depressed", "sad", "happy",
    "need to talk", "can we talk", "listen to me",
)


def _normalize(text: str) -> str:
    """Normalize text for matching."""
    return (text or "").strip().lower()


def _contains_year(text: str, years: Set[str]) -> bool:
    """Check if text contains any of the specified years."""
    text_lower = _normalize(text)
    for year in years:
        # Match year as whole word to avoid false positives
        if re.search(rf'\b{year}\b', text_lower):
            return True
    return False


def _count_keyword_matches(text: str, keywords: Set[str]) -> Tuple[int, List[str]]:
    """Count keyword matches and return matched keywords."""
    text_lower = _normalize(text)
    matched = []
    for kw in keywords:
        if kw in text_lower:
            matched.append(kw)
    return len(matched), matched


def _matches_phrase(text: str, phrases: Tuple[str, ...]) -> Tuple[bool, List[str]]:
    """Check if text starts with or contains any phrase."""
    text_lower = _normalize(text)
    matched = []
    for phrase in phrases:
        if phrase in text_lower:
            matched.append(phrase)
    return len(matched) > 0, matched


def should_search_heuristic(query: str) -> WebSearchDecision:
    """
    Determine if query needs web search using heuristics only.

    Scoring approach:
    - Explicit search phrases: +0.6 confidence
    - Strong recency keywords: +0.4 per match (max 2)
    - Moderate recency keywords: +0.2 per match (max 2)
    - Current year mention: +0.3
    - News keywords: +0.2 per match (max 2)
    - Fast-changing topics: +0.3 per match (max 2)
    - Static topics: -0.3 per match
    - Suppression patterns: -0.5

    Returns:
        WebSearchDecision with confidence and recommendation
    """
    if not query:
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason="Empty query",
            matched_keywords=[],
            matched_patterns=[]
        )

    confidence = 0.0
    all_matched_keywords: List[str] = []
    all_matched_patterns: List[str] = []
    reasons: List[str] = []

    query_lower = _normalize(query)

    # Check suppression patterns first
    suppressed, supp_matches = _matches_phrase(query, SUPPRESSION_PATTERNS)
    if suppressed:
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason=f"Suppressed: matches personal/conversational pattern",
            matched_keywords=[],
            matched_patterns=supp_matches
        )

    # Check explicit search phrases (strongest signal)
    has_explicit, explicit_matches = _matches_phrase(query, EXPLICIT_SEARCH_PHRASES)
    if has_explicit:
        confidence += 0.6
        all_matched_patterns.extend(explicit_matches)
        reasons.append("explicit search request")

    # Strong recency keywords
    strong_count, strong_matches = _count_keyword_matches(query, RECENCY_KEYWORDS_STRONG)
    if strong_count > 0:
        confidence += min(strong_count * 0.4, 0.8)
        all_matched_keywords.extend(strong_matches)
        reasons.append(f"{strong_count} strong recency keyword(s)")

    # Moderate recency keywords
    mod_count, mod_matches = _count_keyword_matches(query, RECENCY_KEYWORDS_MODERATE)
    if mod_count > 0:
        confidence += min(mod_count * 0.2, 0.4)
        all_matched_keywords.extend(mod_matches)
        reasons.append(f"{mod_count} moderate recency keyword(s)")

    # Current/recent year mention
    if _contains_year(query, RECENT_YEARS):
        confidence += 0.3
        all_matched_keywords.append(f"year:{list(RECENT_YEARS)}")
        reasons.append("mentions current/recent year")

    # News keywords
    news_count, news_matches = _count_keyword_matches(query, NEWS_KEYWORDS)
    if news_count > 0:
        confidence += min(news_count * 0.2, 0.4)
        all_matched_keywords.extend(news_matches)
        reasons.append(f"{news_count} news keyword(s)")

    # Fast-changing topics
    fast_count, fast_matches = _count_keyword_matches(query, FAST_CHANGING_TOPICS)
    if fast_count > 0:
        confidence += min(fast_count * 0.3, 0.6)
        all_matched_keywords.extend(fast_matches)
        reasons.append(f"{fast_count} fast-changing topic(s)")

    # Static topics (reduce confidence) - but only if no strong positive signals
    # Strong positive signals: strong recency keywords, fast-changing topics, or explicit search
    has_strong_positive_signals = strong_count > 0 or fast_count > 0 or has_explicit
    static_count, static_matches = _count_keyword_matches(query, STATIC_TOPICS)
    if static_count > 0 and not has_strong_positive_signals:
        confidence -= min(static_count * 0.3, 0.6)
        reasons.append(f"{static_count} static topic(s) (-)")
    elif static_count > 0 and has_strong_positive_signals:
        # Reduced penalty when strong positive signals present
        confidence -= min(static_count * 0.1, 0.2)
        reasons.append(f"{static_count} static topic(s) (reduced penalty due to strong signals)")

    # Clamp confidence
    confidence = max(0.0, min(1.0, confidence))

    # Determine search depth based on confidence and query characteristics
    if confidence >= 0.8 or has_explicit:
        depth = WebSearchDepth.STANDARD
    elif confidence >= 0.6 and fast_count >= 2:
        depth = WebSearchDepth.STANDARD
    elif confidence >= 0.5:
        depth = WebSearchDepth.QUICK
    else:
        depth = WebSearchDepth.QUICK

    # Build reason string
    reason = "; ".join(reasons) if reasons else "No strong indicators"

    should_search = confidence >= SEARCH_CONFIDENCE_THRESHOLD

    logger.debug(
        f"[WebSearchTrigger] Query: '{query[:50]}...' | "
        f"confidence={confidence:.2f} | should_search={should_search} | "
        f"depth={depth.value} | reason={reason}"
    )

    return WebSearchDecision(
        should_search=should_search,
        depth=depth,
        confidence=confidence,
        reason=reason,
        matched_keywords=all_matched_keywords,
        matched_patterns=all_matched_patterns
    )


async def should_search_with_llm(
    query: str,
    model_manager=None,
    heuristic_first: bool = True
) -> WebSearchDecision:
    """
    Determine if query needs web search, optionally using LLM for ambiguous cases.

    Args:
        query: User query text
        model_manager: Optional ModelManager for LLM classification
        heuristic_first: If True, only use LLM if heuristics are uncertain

    Returns:
        WebSearchDecision with final recommendation
    """
    # Always run heuristics first
    heuristic_result = should_search_heuristic(query)

    # If heuristics are confident (high or low), use that result
    if heuristic_first:
        if heuristic_result.confidence >= 0.7 or heuristic_result.confidence <= 0.2:
            return heuristic_result

    # For uncertain cases, try LLM if available
    if model_manager is not None:
        try:
            llm_result = await _classify_with_llm(query, model_manager)
            if llm_result is not None:
                # Combine heuristic and LLM signals
                combined_confidence = (heuristic_result.confidence + llm_result) / 2
                should_search = combined_confidence >= SEARCH_CONFIDENCE_THRESHOLD

                # Adjust depth based on combined confidence
                if combined_confidence >= 0.7:
                    depth = WebSearchDepth.STANDARD
                else:
                    depth = WebSearchDepth.QUICK

                return WebSearchDecision(
                    should_search=should_search,
                    depth=depth,
                    confidence=combined_confidence,
                    reason=f"{heuristic_result.reason}; LLM confidence={llm_result:.2f}",
                    matched_keywords=heuristic_result.matched_keywords,
                    matched_patterns=heuristic_result.matched_patterns
                )
        except asyncio.TimeoutError:
            logger.debug("[WebSearchTrigger] LLM classification timed out")
        except Exception as e:
            logger.debug(f"[WebSearchTrigger] LLM classification failed: {e}")

    return heuristic_result


async def _classify_with_llm(query: str, model_manager) -> Optional[float]:
    """
    Use LLM to classify if query needs web search.

    Args:
        query: User query
        model_manager: ModelManager instance

    Returns:
        Confidence score (0.0-1.0) or None if classification failed
    """
    if not model_manager:
        return None

    prompt = f"""Classify if this query requires CURRENT/LIVE web information or can be answered with general knowledge.

Query: "{query[:500]}"

Consider:
- Does it ask about recent events, news, or current data?
- Does it need real-time information (prices, weather, scores)?
- Does it reference specific recent dates or "latest/current" information?
- Or can it be answered with general/historical knowledge?

Respond with ONLY a number from 0-10:
- 0-3: General knowledge is sufficient
- 4-6: Might benefit from web search
- 7-10: Definitely needs current web information

Number:"""

    try:
        response = await asyncio.wait_for(
            model_manager.generate_once(
                prompt,
                max_tokens=SEARCH_TRIGGER_MAX_TOKENS
            ),
            timeout=SEARCH_TRIGGER_TIMEOUT
        )

        if not response:
            return None

        # Parse numeric response
        response = response.strip()
        match = re.search(r'\b(\d+)\b', response)
        if match:
            score = int(match.group(1))
            return min(max(score / 10.0, 0.0), 1.0)

        return None

    except Exception as e:
        logger.debug(f"[WebSearchTrigger] LLM parse error: {e}")
        return None


def analyze_for_web_search(query: str) -> WebSearchDecision:
    """
    Synchronous convenience function for web search trigger analysis.

    Usage:
        decision = analyze_for_web_search("What's the latest news on AI?")
        if decision.should_search:
            # Trigger web search with decision.depth
            pass
    """
    return should_search_heuristic(query)


# ===== Integration Helpers =====

def get_search_decision_for_prompt(
    query: str,
    crisis_level: Optional[str] = None,
    web_search_enabled: bool = True
) -> WebSearchDecision:
    """
    Get search decision with additional context filtering.

    Args:
        query: User query
        crisis_level: Current tone/crisis level
        web_search_enabled: Whether web search is enabled in config

    Returns:
        WebSearchDecision (may have should_search=False due to suppression)
    """
    # Quick exits
    if not web_search_enabled:
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason="Web search disabled in config",
            matched_keywords=[],
            matched_patterns=[]
        )

    # Crisis suppression
    if crisis_level and crisis_level.upper() in ("HIGH", "MEDIUM"):
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason=f"Suppressed during {crisis_level} crisis level",
            matched_keywords=[],
            matched_patterns=[]
        )

    return should_search_heuristic(query)


# ===== LLM-First Trigger System =====


def quick_prefilter_should_skip(query: str) -> bool:
    """
    Quick pre-filter to skip LLM for obvious non-search queries.

    This runs in <1ms and catches queries that definitely don't need
    web search, avoiding unnecessary LLM calls.

    Args:
        query: User query text

    Returns:
        True if we should SKIP the LLM and not search, False to continue
    """
    if not query or len(query.strip()) < 5:
        return True  # Too short to be a meaningful search

    query_lower = query.lower().strip()

    # Check suppression patterns (personal/emotional queries)
    for pattern in SUPPRESSION_PATTERNS:
        if pattern in query_lower:
            return True

    # Very short conversational queries
    if len(query_lower) < 20 and any(
        query_lower.startswith(p) for p in
        ("hi", "hello", "hey", "thanks", "thank you", "ok", "okay", "sure", "yes", "no", "yeah", "nah")
    ):
        return True

    # Deictic follow-up references - these refer to conversation context, not web content
    # Patterns like "i just watched it", "saw that", "read it", etc.
    deictic_followup_patterns = (
        "watched it", "saw it", "read it", "heard it", "checked it",
        "finished it", "started it", "looked at it",
        "watched that", "saw that", "read that", "heard that",
        "just watched", "just saw", "just read", "just heard",
        "i watched", "i saw", "i read",
    )
    if any(pattern in query_lower for pattern in deictic_followup_patterns):
        logger.debug(f"[WebSearchTrigger] Prefilter: skipping deictic follow-up: {query[:50]}")
        return True

    return False


def _build_llm_trigger_prompt(query: str, current_date: str, remaining_credits: float = 100) -> str:
    """
    Build the classification prompt for the unified LLM trigger.

    Args:
        query: User query text
        current_date: Current date string (e.g., "2026-01-06")
        remaining_credits: Available search credits (affects num_searches suggestion)

    Returns:
        Formatted prompt string for LLM
    """
    return f"""Analyze if this query needs real-time web search OR stored memory search, and generate optimized search terms.

Query: "{query[:500]}"
Current date: {current_date}
Available search budget: {remaining_credits:.0f} credits

WEB SEARCH CRITERIA:
- SEARCH if: current events, recent news, live data (stocks, weather, sports), time-sensitive health info, or references dates/years needing verification
- DON'T SEARCH if: historical facts, scientific concepts, how-to guides, personal/emotional topics, or can be answered with general knowledge
- NEVER SEARCH for:
  * Casual acknowledgments (nice, thanks, cool, got it, okay)
  * Meta-comments about the conversation or system
  * Greetings or short responses under 5 words that aren't explicit search requests
  * Follow-up references to prior conversation ("watched it", "saw that", "just read it", "i just watched", etc.) - these refer to something already discussed, not web content
  * Comments about media the user consumed ("i just watched", "i finished reading", "just saw") - these are conversation follow-ups, not search requests

MEMORY SEARCH CRITERIA (needs_memory_search):
- TRUE if: the user wants to recall past conversations, stored facts about themselves or people they know, personal notes, uploaded documents, or anything from their history with this assistant
- Examples: "tell me more about Flapjack", "what was that thing we discussed?", "remind me about my dog", "what do my notes say about X", "what have I told you about my job"
- FALSE if: general knowledge question, web search query, casual chat, or creative request

OUTPUT (JSON only, no markdown):
{{
  "should_search": true or false,
  "confidence": 0.0-1.0,
  "reason": "brief explanation",
  "search_terms": ["optimized query 1", "optimized query 2"],
  "search_depth": "quick" or "standard" or "deep",
  "num_searches": 1-4,
  "needs_memory_search": true or false
}}

GUIDELINES:
- search_terms: Rewrite for better results (add year if relevant, be specific, remove conversational filler)
- num_searches: Use 2-4 only for comparison queries or multi-faceted topics
- search_depth: "quick" for simple facts, "standard" for news/analysis, "deep" for research
- If not searching, return empty search_terms and num_searches: 0
- needs_memory_search and should_search can both be false, but not both true (web vs memory are separate paths)

JSON:"""


async def _classify_with_llm_unified(
    query: str,
    model_manager,
    remaining_credits: float = 100,
    timeout: float = None
) -> Optional[LLMSearchTriggerResponse]:
    """
    Unified LLM call for search trigger classification.

    This is the core LLM-first classification that returns structured
    output including search terms, depth, and number of searches.

    Args:
        query: User query text
        model_manager: ModelManager instance for LLM calls
        remaining_credits: Available credits (affects num_searches)
        timeout: Override default timeout

    Returns:
        LLMSearchTriggerResponse if successful, None if failed/timeout
    """
    if not model_manager:
        return None

    current_date = datetime.now().strftime("%Y-%m-%d")
    prompt = _build_llm_trigger_prompt(query, current_date, remaining_credits)
    effective_timeout = timeout or SEARCH_TRIGGER_TIMEOUT

    logger.debug(
        f"[WebSearchTrigger] Calling LLM: model={SEARCH_TRIGGER_MODEL}, "
        f"timeout={effective_timeout}s, max_tokens={SEARCH_TRIGGER_MAX_TOKENS}"
    )

    try:
        response = await asyncio.wait_for(
            model_manager.generate_once(
                prompt,
                model_name=SEARCH_TRIGGER_MODEL,
                max_tokens=SEARCH_TRIGGER_MAX_TOKENS,
                temperature=0.0  # Deterministic for consistent decisions
            ),
            timeout=effective_timeout
        )

        if not response:
            logger.debug("[WebSearchTrigger] LLM returned empty response")
            return None

        logger.debug(f"[WebSearchTrigger] LLM raw response: {response[:200]}...")
        parsed = LLMSearchTriggerResponse.parse(response)
        if parsed:
            logger.debug(
                f"[WebSearchTrigger] LLM parsed: should_search={parsed.should_search}, "
                f"conf={parsed.confidence}, terms={parsed.search_terms}"
            )
        return parsed

    except asyncio.TimeoutError:
        logger.warning(f"[WebSearchTrigger] LLM classification timed out after {effective_timeout}s")
        return None
    except Exception as e:
        logger.warning(f"[WebSearchTrigger] LLM classification error: {e}")
        return None


async def analyze_for_web_search_llm(
    query: str,
    model_manager=None,
    crisis_level: Optional[str] = None,
    web_search_enabled: bool = True,
    remaining_credits: float = 100,
    timeout: float = None
) -> WebSearchDecision:
    """
    LLM-first web search trigger analysis with heuristic fallback.

    This is the primary entry point for determining if a query needs web search.
    Uses LLM classification first, with 70/30 confidence blend with heuristics.
    Falls back to pure heuristics on LLM timeout or error.

    Flow:
    1. Crisis level check (HIGH/MEDIUM suppresses search)
    2. Quick pre-filter (skip obvious non-search queries)
    3. LLM classification (returns should_search + search_terms + depth)
    4. Blend: 70% LLM + 30% heuristic confidence
    5. Fallback: Pure heuristics on LLM failure

    Args:
        query: User query text
        model_manager: ModelManager instance for LLM calls (optional)
        crisis_level: Current tone/crisis level from ToneDetector
        web_search_enabled: Whether web search is enabled in config
        remaining_credits: Available credits for search (affects num_searches)
        timeout: Override default LLM timeout

    Returns:
        WebSearchDecision with should_search, search_terms, depth, num_searches
    """
    global _llm_trigger_cache

    # Check cache first (prevents duplicate LLM calls within same request)
    # Only hash on query - crisis_level may differ between callers but decision is same
    cache_key = hash(query)
    now = time.time()
    if cache_key in _llm_trigger_cache:
        cached_time, cached_result = _llm_trigger_cache[cache_key]
        if now - cached_time < _LLM_TRIGGER_CACHE_TTL:
            logger.debug(f"[WebSearchTrigger] Cache hit for query (age={now - cached_time:.2f}s)")
            return cached_result

    # Clean expired cache entries periodically (every ~100 calls)
    if len(_llm_trigger_cache) > 50:
        _llm_trigger_cache = {
            k: v for k, v in _llm_trigger_cache.items()
            if now - v[0] < _LLM_TRIGGER_CACHE_TTL
        }

    # Quick exits
    if not web_search_enabled:
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason="Web search disabled in config",
            matched_keywords=[],
            matched_patterns=[],
            source="heuristic"
        )

    # Crisis suppression
    if crisis_level and crisis_level.upper() in ("HIGH", "MEDIUM"):
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason=f"Suppressed during {crisis_level} crisis level",
            matched_keywords=[],
            matched_patterns=[],
            source="heuristic"
        )

    # Quick pre-filter: skip LLM for obvious non-search queries
    if quick_prefilter_should_skip(query):
        return WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=0.0,
            reason="Pre-filter: query unlikely to need search",
            matched_keywords=[],
            matched_patterns=[],
            source="heuristic"
        )

    # Always compute heuristic result (used for blending and fallback)
    heuristic_result = should_search_heuristic(query)

    # If LLM-first mode is disabled or no model manager, use heuristics only
    if not LLM_FIRST_ENABLED or model_manager is None:
        return heuristic_result

    # Try LLM classification
    llm_response = await _classify_with_llm_unified(
        query,
        model_manager,
        remaining_credits,
        timeout
    )

    # If LLM failed, fall back to heuristics
    if llm_response is None:
        logger.debug("[WebSearchTrigger] LLM failed, falling back to heuristics")
        return heuristic_result

    # Heuristic veto: only override LLM when heuristic has an ACTIVE reason
    # to suppress (matched a suppression/static pattern). A confidence of 0.0
    # with "No strong indicators" means the heuristic has no opinion — not a
    # confident "no" — so it should not block the LLM.
    has_active_suppression = (
        heuristic_result.matched_patterns  # matched a suppression pattern
        or "static topic" in heuristic_result.reason  # matched static topics
    )
    if has_active_suppression and not heuristic_result.should_search:
        logger.debug(
            f"[WebSearchTrigger] Heuristic veto: active suppression detected "
            f"(reason={heuristic_result.reason}), LLM wanted search={llm_response.should_search} but heuristic says no"
        )
        veto_result = WebSearchDecision(
            should_search=False,
            depth=WebSearchDepth.QUICK,
            confidence=heuristic_result.confidence,
            reason=f"Heuristic veto ({heuristic_result.reason}); LLM overridden",
            matched_keywords=heuristic_result.matched_keywords,
            matched_patterns=heuristic_result.matched_patterns,
            search_terms=[],
            num_searches=0,
            source="heuristic"
        )
        _llm_trigger_cache[cache_key] = (time.time(), veto_result)
        return veto_result

    # Convert LLM confidence to directional search score.
    # confidence=0.90 + should_search=False means "90% sure we DON'T need search" → search_score=0.10
    # confidence=0.90 + should_search=True means "90% sure we DO need search" → search_score=0.90
    llm_search_score = llm_response.confidence if llm_response.should_search else (1.0 - llm_response.confidence)

    # Blend directional LLM score with heuristic confidence (70% LLM, 30% heuristic)
    llm_weight = LLM_HEURISTIC_BLEND_WEIGHT
    heuristic_weight = 1.0 - llm_weight
    blended_confidence = (
        llm_weight * llm_search_score +
        heuristic_weight * heuristic_result.confidence
    )

    # Determine final should_search based on blended confidence
    should_search = blended_confidence >= SEARCH_CONFIDENCE_THRESHOLD

    # High-confidence LLM override: if LLM is very confident (>=0.8) in either
    # direction, trust it directly — the heuristic having no opinion (0.0)
    # should not block a definitive LLM decision
    if llm_response.confidence >= 0.8:
        should_search = llm_response.should_search

    # Map LLM depth string to enum
    depth_map = {
        "quick": WebSearchDepth.QUICK,
        "standard": WebSearchDepth.STANDARD,
        "deep": WebSearchDepth.DEEP
    }
    depth = depth_map.get(llm_response.search_depth, WebSearchDepth.QUICK)

    # Build combined reason
    reason = (
        f"LLM: {llm_response.reason} (conf={llm_response.confidence:.2f}); "
        f"Heuristic: {heuristic_result.reason} (conf={heuristic_result.confidence:.2f}); "
        f"Blended={blended_confidence:.2f}"
    )

    logger.debug(
        f"[WebSearchTrigger] LLM-first result: should_search={should_search}, "
        f"terms={llm_response.search_terms}, depth={depth.value}, "
        f"blended_conf={blended_confidence:.2f}"
    )

    result = WebSearchDecision(
        should_search=should_search,
        depth=depth,
        confidence=blended_confidence,
        reason=reason,
        matched_keywords=heuristic_result.matched_keywords,
        matched_patterns=heuristic_result.matched_patterns,
        search_terms=llm_response.search_terms if should_search else [],
        num_searches=llm_response.num_searches if should_search else 0,
        source="llm",
        needs_memory_search=llm_response.needs_memory_search
    )

    # Cache the result to avoid duplicate LLM calls within same request
    _llm_trigger_cache[cache_key] = (time.time(), result)

    return result


if __name__ == "__main__":
    # Quick test
    import logging
    logging.basicConfig(level=logging.DEBUG)

    test_queries = [
        "What's the latest news on AI?",
        "current bitcoin price",
        "weather forecast for tomorrow",
        "who was the first president of the united states",
        "how do I feel today",
        "search for python tutorials",
        "what's happening with the stock market 2024",
        "explain quantum computing",
        "latest iPhone release date",
        "how to make pasta",
    ]

    for q in test_queries:
        result = analyze_for_web_search(q)
        print(f"\nQuery: {q}")
        print(f"  Should search: {result.should_search}")
        print(f"  Confidence: {result.confidence:.2f}")
        print(f"  Depth: {result.depth.value}")
        print(f"  Reason: {result.reason}")
