"""Regression tests for the 2026-09-08 answer-call receipt export (B4, F7).

The exported debug `prompt`/`system_prompt` fields are the BASE retrieval
prompt, but an agentic turn's answer is actually generated by
`controller._build_final_prompt` — which can render a materially different
set of sections (record 40 in the 2026-09-08 dump: the base prompt rendered
[GOOGLE CALENDAR] + [KNOWLEDGE GRAPH] while the answering call's own receipt
said both were omitted). `_build_debug_record` now accepts an `extra` dict
that the agentic path fills with `answer_call`/`answer_prompt`/
`answer_system_prompt`/`answer_prompt_tokens`/`answer_prompt_hash`, and
`build_redacted_prompt_export` renders that payload first under an
"ANSWERING CALL" heading before the existing "BASE RETRIEVAL PROMPT"
sections. Legacy records without the field must export unchanged.

Synthetic values throughout (no real people/documents).
"""

import hashlib
from unittest.mock import MagicMock

import pytest

from tests.unit.test_handle_submit import _debug_record, _make_orchestrator, _run_submit
from utils.privacy_redaction import build_redacted_prompt_export, redact_data


# ---------------------------------------------------------------------------
# Debug record gains the answer-call receipt fields on an agentic turn.
# ---------------------------------------------------------------------------

class TestAgenticDebugRecordAnswerCallFields:
    @pytest.mark.asyncio
    async def test_debug_record_carries_answer_call_receipt(self):
        orch = _make_orchestrator(
            agentic_enabled=True,
            agentic_items=["The 10th Fibonacci number is 55."],
        )
        orch.agentic_controller._last_final_prompt = "FINAL_PROMPT_MARKER"
        orch.agentic_controller._last_final_system_prompt = "FINAL_SYS_MARKER"
        orch.agentic_controller._last_session = MagicMock(answer_call="final_synthesis")

        results = await _run_submit("calculate fibonacci 10", orch)

        debug = _debug_record(results)
        assert debug is not None
        assert debug["mode"] == "agentic-search"

        # New answer-call fields.
        assert debug["answer_call"] == "final_synthesis"
        assert debug["answer_prompt"] == "FINAL_PROMPT_MARKER"
        assert debug["answer_system_prompt"] == "FINAL_SYS_MARKER"
        assert isinstance(debug["answer_prompt_tokens"], int)
        assert debug["answer_prompt_tokens"] > 0
        assert debug["answer_prompt_hash"] == hashlib.sha256(
            b"FINAL_PROMPT_MARKER"
        ).hexdigest()[:16]

        # Base fields keep their existing names/values (compatibility).
        assert debug["prompt"] == "Test prompt"
        assert debug["system_prompt"] == "Test system prompt"
        assert debug["token_count_kind"] == "local_input_estimate"
        assert "total_tokens" in debug

    @pytest.mark.asyncio
    async def test_no_answer_call_fields_when_controller_has_no_final_prompt(self):
        # Default _make_orchestrator() agentic_controller never sets
        # _last_final_prompt — the extra must degrade to {} (or just
        # answer_call), never raise and never fall the turn through to
        # enhanced mode.
        orch = _make_orchestrator(
            agentic_enabled=True,
            agentic_items=["The 10th Fibonacci number is 55."],
        )
        results = await _run_submit("calculate fibonacci 10", orch)

        debug = _debug_record(results)
        assert debug is not None
        assert debug["mode"] == "agentic-search"
        assert "answer_prompt" not in debug or not debug.get("answer_prompt")


# ---------------------------------------------------------------------------
# build_redacted_prompt_export: answering-call payload rendered first.
# ---------------------------------------------------------------------------

class TestAnsweringCallExport:
    def _record(self, **overrides):
        base = {
            "mode": "agentic-search",
            "model": "test-model",
            "query": "calculate fibonacci 10",
            "prompt": "BASE_PROMPT_MARKER",
            "system_prompt": "BASE_SYSTEM_MARKER",
        }
        base.update(overrides)
        return base

    def test_answering_call_section_rendered_first_with_system(self):
        record = self._record(
            answer_call="final_synthesis",
            answer_prompt="FINAL_PROMPT_MARKER",
            answer_system_prompt="FINAL_SYS_MARKER",
        )
        exported = build_redacted_prompt_export(record, include_system=True)

        assert "[ANSWERING CALL (final_synthesis)]" in exported
        assert "[BASE RETRIEVAL PROMPT]" in exported
        assert "FINAL_PROMPT_MARKER" in exported
        assert "FINAL_SYS_MARKER" in exported
        assert "BASE_PROMPT_MARKER" in exported
        assert "BASE_SYSTEM_MARKER" in exported

        # Answering payload comes before the base retrieval section.
        assert exported.index("[ANSWERING CALL") < exported.index("[BASE RETRIEVAL PROMPT]")
        assert exported.index("FINAL_PROMPT_MARKER") < exported.index("BASE_PROMPT_MARKER")

    def test_include_system_false_omits_both_system_prompts(self):
        record = self._record(
            answer_call="final_synthesis",
            answer_prompt="FINAL_PROMPT_MARKER",
            answer_system_prompt="FINAL_SYS_MARKER",
        )
        exported = build_redacted_prompt_export(record, include_system=False)

        assert "[ANSWERING CALL SYSTEM PROMPT]" not in exported
        assert "[SYSTEM PROMPT]" not in exported
        assert "FINAL_SYS_MARKER" not in exported
        assert "BASE_SYSTEM_MARKER" not in exported
        # The answering prompt body itself (not its system prompt) still shows.
        assert "[ANSWERING CALL (final_synthesis)]" in exported
        assert "FINAL_PROMPT_MARKER" in exported
        assert "BASE_PROMPT_MARKER" in exported

    def test_legacy_record_without_answer_prompt_exports_unchanged(self):
        legacy = self._record()  # no answer_call/answer_prompt/answer_system_prompt
        with_field_removed = build_redacted_prompt_export(legacy, include_system=True)

        # Exactly the pre-existing shape: no answering-call section at all.
        assert "ANSWERING CALL" not in with_field_removed
        assert "BASE RETRIEVAL PROMPT" not in with_field_removed
        assert "[SYSTEM PROMPT]" in with_field_removed
        assert "[USER QUERY]" in with_field_removed
        assert "[FULL CONTEXT PROMPT]" in with_field_removed
        assert "BASE_SYSTEM_MARKER" in with_field_removed
        assert "BASE_PROMPT_MARKER" in with_field_removed

        # And it is byte-identical to calling the function again (determinism).
        assert with_field_removed == build_redacted_prompt_export(legacy, include_system=True)

    def test_answer_prompt_hash_survives_redaction_unchanged(self):
        answer_prompt = "FINAL_PROMPT_MARKER"
        answer_prompt_hash = hashlib.sha256(answer_prompt.encode()).hexdigest()[:16]
        record = self._record(
            answer_call="final_synthesis",
            answer_prompt=answer_prompt,
            answer_system_prompt="FINAL_SYS_MARKER",
            answer_prompt_hash=answer_prompt_hash,
            answer_prompt_tokens=42,
        )
        redacted = redact_data(record)
        assert redacted["answer_prompt_hash"] == answer_prompt_hash
        assert redacted["answer_prompt_tokens"] == 42
